# Generated by Django 3.2 on 2021-04-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=256)),
                ('district', models.CharField(choices=[('CW', 'Central and Western'), ('E', 'Eastern'), ('S', 'Southern'), ('WC', 'Wan Chai'), ('SSP', 'Sham Shui Po'), ('KC', 'Kowloon City'), ('KWT', 'Kwun Tong'), ('WTS', 'Wong Tai Sin'), ('YTM', 'Yau Tsim Wong'), ('I', 'Islands'), ('KTS', 'Kwai Tsing'), ('N', 'North'), ('SK', 'Sai Kung'), ('ST', 'Sha Tin'), ('TP', 'Tai Po'), ('TW', 'Tsuen Wan'), ('TM', 'Tuen Mun'), ('YL', 'Yuen Long')], max_length=256)),
                ('open_public_holidays', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='doctors_api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcp47', models.CharField(max_length=256)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='doctors_api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('d', 'Dentist'), ('cm', 'Chinese Medicine'), ('a', 'Acupuncture'), ('c', 'Chiropractor')], max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.TextField(max_length=3)),
                ('desc_en', models.TextField(max_length=256)),
                ('desc_yue', models.TextField(max_length=256)),
                ('note_en', models.TextField(max_length=256)),
                ('note_yue', models.TextField(max_length=256)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='doctors_api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAddressLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcp47', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='doctors_api.doctor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='doctorlanguage',
            constraint=models.UniqueConstraint(fields=('doctor', 'bcp47'), name='doctor_language'),
        ),
        migrations.AddConstraint(
            model_name='doctoraddresslanguage',
            constraint=models.UniqueConstraint(fields=('doctor', 'bcp47'), name='doctor_address_language'),
        ),
    ]
